// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: proto/unproc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UnprocClient is the client API for Unproc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnprocClient interface {
	Retrieve(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserReply, error)
}

type unprocClient struct {
	cc grpc.ClientConnInterface
}

func NewUnprocClient(cc grpc.ClientConnInterface) UnprocClient {
	return &unprocClient{cc}
}

func (c *unprocClient) Retrieve(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/unproc.Unproc/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnprocServer is the server API for Unproc service.
// All implementations must embed UnimplementedUnprocServer
// for forward compatibility
type UnprocServer interface {
	Retrieve(context.Context, *User) (*UserReply, error)
	mustEmbedUnimplementedUnprocServer()
}

// UnimplementedUnprocServer must be embedded to have forward compatible implementations.
type UnimplementedUnprocServer struct {
}

func (UnimplementedUnprocServer) Retrieve(context.Context, *User) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedUnprocServer) mustEmbedUnimplementedUnprocServer() {}

// UnsafeUnprocServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnprocServer will
// result in compilation errors.
type UnsafeUnprocServer interface {
	mustEmbedUnimplementedUnprocServer()
}

func RegisterUnprocServer(s grpc.ServiceRegistrar, srv UnprocServer) {
	s.RegisterService(&Unproc_ServiceDesc, srv)
}

func _Unproc_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnprocServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unproc.Unproc/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnprocServer).Retrieve(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// Unproc_ServiceDesc is the grpc.ServiceDesc for Unproc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Unproc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unproc.Unproc",
	HandlerType: (*UnprocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _Unproc_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/unproc.proto",
}
